### ISSUE TITLE
ERROR: Command "python setup.py egg_info" failed

### ISSUE THREAD

**Issue by JiaxiangBU** [hanzhichao2000/pysentiment#10]
```bash
$ pip install pysentiment
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pysentiment
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/3d/32/b9822555aeafd949ba2e1e5f0ca9a7aea857802965c61a6290e711b11e6c/pysentiment-0.2.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\LIJIAX~1\AppData\Local\Temp\pip-install-lqrdhnbk\pysentiment\setup.py", line 8, in <module>
        install_req = [e.strip() for e in open(path_req).readlines()]
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\LIJIAX~1\\AppData\\Local\\Temp\\pip-install-lqrdhnbk\\pysentiment\\requirements.txt'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\LIJIAX~1\AppData\Local\Temp\pip-install-lqrdhnbk\pysentiment\
```

```bash
$ pip --version
pip 19.1.1 from D:\install\miniconda\lib\site-packages\pip (python 3.7)
```

**Comment by JiaxiangBU** [comment]
However, when I download and install it locally, it works.

```bash
$ cd pysentiment/
$ pip install .
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing d:\work\pysentiment
Requirement already satisfied: pandas>=0.10 in c:\users\lijiaxiang\appdata\roaming\python\python37\site-packages (from pysentiment==0.2) (0.25.3)
Requirement already satisfied: nltk>=2.0 in d:\install\miniconda\lib\site-packages (from pysentiment==0.2) (3.4.5)
Requirement already satisfied: numpy>=1.13.3 in c:\users\lijiaxiang\appdata\roaming\python\python37\site-packages (from pandas>=0.10->pysentiment==0.2) (1.18.2)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\lijiaxiang\appdata\roaming\python\python37\site-packages (from pandas>=0.10->pysentiment==0.2) (2.7.5)
Requirement already satisfied: pytz>=2017.2 in d:\install\miniconda\lib\site-packages (from pandas>=0.10->pysentiment==0.2) (2018.7)
Requirement already satisfied: six in d:\install\miniconda\lib\site-packages (from nltk>=2.0->pysentiment==0.2) (1.12.0)
Building wheels for collected packages: pysentiment
  Building wheel for pysentiment (setup.py) ... done
  Stored in directory: C:\Users\LIJIAX~1\AppData\Local\Temp\pip-ephem-wheel-cache-0jcig2nr\wheels\d5\60\a8\279e726168e860a96d34ef1cdbd4759307ef9473ebe2da49af
Successfully built pysentiment
Installing collected packages: pysentiment
Successfully installed pysentiment-0.2
```
