### ISSUE TITLE
Error with Installation. 

### ISSUE THREAD

**Issue by huileiw** [hanzhichao2000/pysentiment#13]
(py36) bash-3.2$ pip install pysentiment
Collecting pysentiment
  Using cached https://files.pythonhosted.org/packages/3d/32/b9822555aeafd949ba2e1e5f0ca9a7aea857802965c61a6290e711b11e6c/pysentiment-0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/2n/3jnbv29510n3ld2t0fqk6xhm0000gn/T/pip-install-cjoj1h33/pysentiment/setup.py", line 8, in <module>
        install_req = [e.strip() for e in open(path_req).readlines()]
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/2n/3jnbv29510n3ld2t0fqk6xhm0000gn/T/pip-install-cjoj1h33/pysentiment/requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/2n/3jnbv29510n3ld2t0fqk6xhm0000gn/T/pip-install-cjoj1h33/pysentiment/
(py36) bash-3.2$

**Comment by cantabile-kwok** [comment]
It can probably be solved if install from source. Download zip and run `python setup.py install`.

**Comment by ntavares** [comment]
Try:
```
python3 -m pip install git+https://github.com/hanzhichao2000/pysentiment
```
