### ISSUE TITLE
utf-8 codec cannot decode error

### ISSUE THREAD

**Issue by tpof314** [hanzhichao2000/pysentiment#4]
I got the following error:

Traceback (most recent call last):
  File "sentiment_test.py", line 4, in <module>
    lm = ps.LM()
  File "/usr/local/lib/python3.5/dist-packages/pysentiment-0.1.2.1-py3.5.egg/pysentiment/base.py", line 54, in **init**
    self._tokenizer = Tokenizer()
  File "/usr/local/lib/python3.5/dist-packages/pysentiment-0.1.2.1-py3.5.egg/pysentiment/utils.py", line 39, in __init__
    self._stopset = self.get_stopset()
  File "/usr/local/lib/python3.5/dist-packages/pysentiment-0.1.2.1-py3.5.egg/pysentiment/utils.py", line 56, in get_stopset
    for line in fin.readlines():
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 184: invalid continuation byte

**Comment by oaraque** [comment]
I got the same problem as you with the version that pip install for py3.5. The problem is at file utils.py, the reading of the static files is not done properly.

Nevertheless, I think in the problem is solved in the github code. Try using the github code instead of the pip one. This worked for me.

**Comment by atharva-20** [comment]
Hey use ftfy package.
Whatever text you pull from beautiful soup / Newspaper (I am using Goose). 
decode that text using .decode("utf-8")
pass it through ftfy.
encode again using .encode("utf-8")

**Comment by oscarmorrison** [comment]
+1 I had this same issue.

I fixed this by manually installing:

 cloning the repo, then running
`sudo python3 setup.py install` inside the folder.
(then I just deleted folder)

**Comment by hanzhichao2000** [comment]
Latest version is uploaded to pypi.
