### ISSUE TITLE
Unable to download - FileNotFoundError - Not finding requirements.txt

### ISSUE THREAD

**Issue by bradboldenow** [hanzhichao2000/pysentiment#7]
Using python 3.6.5 - using pip install pysentiment - I am getting the following error:
```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\...\AppData\Local\Temp\pip-install-1h2p8ypv\pysentiment\setup.py", line 8, in <module>
        install_req = [e.strip() for e in open(path_req).readlines()]
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\User...Local\\Temp\\pip-install-1h2p8ypv\\pysentiment\\requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\...\AppData\Local\Temp\pip-install-1h2p8ypv\pysentiment\
```

Could anyone help me better understand whats going on here? I updated the setuptools and it still is not working.

**Comment by hemantmenon** [comment]
Try cloning the repo and running `sudo python3 setup.py install`
Should work
